/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate and open a session
         * @description On success the session token is set as an `HttpOnly`, `SameSite=Lax`
         *     cookie. It is **not** returned in the body: putting it there would
         *     hand it to any script on the page, which is what `HttpOnly` exists to
         *     prevent.
         *
         *     The `Secure` attribute is set on any TLS request, and otherwise only
         *     when `auth.cookieSecure` is configured — a browser discards a `Secure`
         *     cookie sent over plain HTTP, which would break a local install. Behind
         *     a proxy that terminates TLS, set that option.
         *
         *     Every failure returns `PIVOT-AUTH-001` with the same message and at
         *     the same cost, whether the account is unknown, the password is wrong,
         *     or the account is disabled. Distinguishing them — in the body or in
         *     the timing — tells an attacker which addresses are real.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Revokes the session immediately: the very next request carrying the
         *     token is rejected, with no window to wait out. That immediacy is why
         *     sessions are server-side rather than stateless tokens.
         *
         *     Succeeds whether or not a valid session was present. The caller asked
         *     to be logged out, and they are.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user and session */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own active sessions
         * @description Returns only the caller's sessions, never anyone else's. The one
         *     making this request is marked `current`.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End one of the caller's own sessions
         * @description Scoped to the caller, not merely to their organization: naming another
         *     member's session returns 404 rather than ending it.
         *
         *     Revoking the session making the request is a logout, and clears the
         *     cookie.
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports only that the process is running and should not be restarted.
         *
         *     It deliberately does **not** consult dependencies: a database outage
         *     must not cause an orchestrator to kill every Pivot pod, which would
         *     turn a recoverable dependency failure into a total outage.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether this instance should receive traffic. Fails while the
         *     instance is shutting down, and whenever a registered dependency check
         *     fails.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The built-in roles and what each may do
         * @description Readable by any authenticated caller: which roles exist and what they
         *     mean is documentation, and a role picker needs it. Who *holds* a role
         *     is a different question, answered by the role-assignments endpoint,
         *     which is gated.
         *
         *     `native_query` appears on Analyst and not on Editor deliberately. Raw
         *     SQL bypasses semantic row-level security, so it is a separate grant
         *     rather than something bundled into "can edit".
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who holds which role
         * @description Requires `manage_roles`.
         */
        get: operations["listRoleAssignments"];
        put?: never;
        /**
         * Give a user or group a role
         * @description Requires `manage_roles` — which is, deliberately, the most dangerous
         *     permission in the API: whoever holds it can grant it to themselves.
         *
         *     Granting the same role twice is a no-op. A subject that does not exist
         *     in the caller's organization is refused as a validation failure rather
         *     than stored as a dangling row.
         */
        post: operations["grantRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/role-assignments/{subjectType}/{subjectId}/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Take a role away
         * @description Requires `manage_roles`.
         *
         *     Removing the **last** administrator is refused: an organization with
         *     nobody who can grant roles is recoverable only from the command line,
         *     and the people most likely to reach that state are the least likely to
         *     have shell access. `pivot admin grant-role` is that recovery path.
         */
        delete: operations["revokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End any session in the organization
         * @description Requires `manage_sessions`. This is the administrative counterpart to
         *     `DELETE /api/v1/auth/sessions/{id}`, which only ever ends the caller's
         *     own: scoped to the organization rather than to one user, it is the
         *     right power for responding to a compromise and the wrong one for
         *     managing your own devices, which is why they are separate endpoints
         *     with separate permissions.
         */
        delete: operations["revokeAnySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @description The organization slug to authenticate against. May be omitted when
             *     the instance hosts exactly one organization, which is the
             *     self-hosted case. With several it is required — defaulting to one
             *     of them would authenticate people against a tenant they never
             *     named.
             * @example acme
             */
            organization?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: email */
            email: string;
            name: string;
            avatarUrl?: string;
            /** @example en */
            locale: string;
            /** @example UTC */
            timezone: string;
            isActive: boolean;
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            issuedAt: string;
            /**
             * Format: date-time
             * @description The idle expiry. It moves forward as the session is used.
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @description The hard cap. Never extended, so an actively used session still
             *     ends — without it, a stolen token stays valid indefinitely as long
             *     as the thief keeps using it.
             */
            absoluteExpiresAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            ip?: string;
            userAgent?: string;
            /** @description Whether this is the session making the request. */
            current: boolean;
        };
        SessionEnvelope: {
            user: components["schemas"]["User"];
            session: components["schemas"]["Session"];
            /**
             * @description What the caller may do in their organization.
             *
             *     **Advisory.** It exists so a UI can hide what it cannot do rather
             *     than letting someone discover it by being refused. Every endpoint
             *     enforces independently, so treating this list as the authority
             *     would be a mistake — and an omission from it is never a way in.
             *
             *     Present on `/auth/me`, absent from the login response.
             * @example [
             *       "view_content",
             *       "query"
             *     ]
             */
            permissions?: string[];
        };
        RoleDescription: {
            /** @example analyst */
            role: string;
            permissions: string[];
        };
        RoleCatalog: {
            roles: components["schemas"]["RoleDescription"][];
        };
        RoleAssignment: {
            /**
             * @description A `group` assignment is a userset: every member of that group holds
             *     the role, including members of groups nested beneath it.
             * @enum {string}
             */
            subjectType: "user" | "group";
            /** Format: uuid */
            subjectId: string;
            /** @example admin */
            role: string;
            /** Format: date-time */
            grantedAt?: string;
        };
        RoleAssignmentList: {
            assignments: components["schemas"]["RoleAssignment"][];
        };
        GrantRoleRequest: {
            /** @enum {string} */
            subjectType: "user" | "group";
            /** Format: uuid */
            subjectId: string;
            /** @enum {string} */
            role: "admin" | "editor" | "analyst" | "viewer";
        };
        SessionList: {
            sessions: components["schemas"]["Session"][];
        };
        HealthResponse: {
            /**
             * @description One of `ok`, `not_ready`, or `shutting_down`.
             * @example ok
             */
            status: string;
            /** @description The running build's version. */
            version: string;
            /** @description Per-dependency results. Present only on the readiness probe. */
            checks?: {
                [key: string]: string;
            };
        };
        ErrorDetail: {
            /**
             * @description The offending field, for validation failures.
             * @example email
             */
            field?: string;
            /** @example is required */
            message: string;
        };
        ErrorBody: {
            /**
             * @description A stable, machine-readable identifier. Independent of the HTTP
             *     status: the status says how the transport should behave, the code
             *     says what went wrong. Branch on this, never on the message.
             * @example PIVOT-REQ-003
             */
            code: string;
            /** @description A human-readable explanation. May change; do not parse it. */
            message: string;
            /** @description Per-field problems, for validation failures. */
            details?: components["schemas"]["ErrorDetail"][];
            /** @description Correlation ID, echoed in the `X-Request-Id` header. */
            requestId?: string;
            /**
             * Format: uri
             * @description Documentation for this error code.
             */
            docs: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description The request was malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required, or the tenant could not be resolved */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated, but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A version conflict or a duplicate */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The body failed validation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited. `Retry-After` gives the wait in seconds. */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description A dependency could not be reached. On a gated endpoint this means the
         *     authorization backend was unavailable, so the request was denied
         *     without a decision being made — deliberately distinguishable from 403,
         *     which means a decision was made and it was no.
         */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; the session cookie is set */
            200: {
                headers: {
                    /** @description The session cookie, `HttpOnly` and `SameSite=Lax`. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            /**
             * @description Throttled, or the account is locked after repeated failures. The
             *     two are the same status and different codes — `PIVOT-RATE-001`
             *     means "slow down", `PIVOT-AUTH-005` means "this account is locked"
             *     — and they call for different handling, so branch on the code.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; the session cookie is cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions, most recent activity first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "1.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready for traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Not ready — shutting down, or a dependency is failing */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "not_ready",
                     *       "version": "1.0.0",
                     *       "checks": {
                     *         "database": "error: connection refused"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleCatalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRoleAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every role assignment in the caller's organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    grantRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRoleRequest"];
            };
        };
        responses: {
            /** @description The role was granted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectType: "user" | "group";
                subjectId: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description The request was rejected — most usefully, because this is the last
             *     administrator.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeAnySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
}
