/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate and open a session
         * @description On success the session token is set as an `HttpOnly`, `SameSite=Lax`
         *     cookie. It is **not** returned in the body: putting it there would
         *     hand it to any script on the page, which is what `HttpOnly` exists to
         *     prevent.
         *
         *     The `Secure` attribute is set on any TLS request, and otherwise only
         *     when `auth.cookieSecure` is configured — a browser discards a `Secure`
         *     cookie sent over plain HTTP, which would break a local install. Behind
         *     a proxy that terminates TLS, set that option.
         *
         *     Every failure returns `PIVOT-AUTH-001` with the same message and at
         *     the same cost, whether the account is unknown, the password is wrong,
         *     or the account is disabled. Distinguishing them — in the body or in
         *     the timing — tells an attacker which addresses are real.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the current session
         * @description Revokes the session immediately: the very next request carrying the
         *     token is rejected, with no window to wait out. That immediacy is why
         *     sessions are server-side rather than stateless tokens.
         *
         *     Succeeds whether or not a valid session was present. The caller asked
         *     to be logged out, and they are.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated user and session */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change your own password
         * @description Proves the current password, stores the new one, and **ends every other
         *     session** — leaving the caller signed in on the device they changed it
         *     from.
         *
         *     Each of those three is deliberate. Verifying the current password is
         *     what stops an unlocked laptop or an XSS bug from being enough to take
         *     an account: a session cookie is not a re-authentication. Ending the
         *     other sessions is the point of the operation, since a password change
         *     is usually a response to suspicion and one that leaves the other
         *     party's session alive has done nothing. Keeping this one means the safe
         *     action does not feel like a punishment.
         *
         *     A wrong current password is **422 against the field**, not 401. A 401
         *     would send a browser's global session handling to the login page,
         *     signing somebody out because they mistyped their own password into a
         *     form.
         *
         *     This is not `pivot admin reset-password`, which exists for somebody who
         *     cannot prove anything and ends every session including the one in use.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The caller's own active sessions
         * @description Returns only the caller's sessions, never anyone else's. The one
         *     making this request is marked `current`.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End one of the caller's own sessions
         * @description Scoped to the caller, not merely to their organization: naming another
         *     member's session returns 404 rather than ending it.
         *
         *     Revoking the session making the request is a logout, and clears the
         *     cookie.
         */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Reports only that the process is running and should not be restarted.
         *
         *     It deliberately does **not** consult dependencies: a database outage
         *     must not cause an orchestrator to kill every Pivot pod, which would
         *     turn a recoverable dependency failure into a total outage.
         */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Reports whether this instance should receive traffic. Fails while the
         *     instance is shutting down, and whenever a registered dependency check
         *     fails.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The single sign-on buttons a login page should offer
         * @description Unauthenticated by necessity: the login page needs these before anyone
         *     has a session. It therefore returns the slug and display name and
         *     nothing else — issuer and client id are not secret, but publishing an
         *     organization's vendor relationships to anonymous callers buys nothing.
         *
         *     An unresolvable organization returns an empty list rather than an
         *     error, which is true and reveals nothing about which organizations
         *     exist.
         */
        get: operations["listAuthProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Begin a single sign-on login
         * @description Redirects the browser to the identity provider, and sets a short-lived
         *     `HttpOnly` cookie holding this login's `state`, `nonce` and PKCE
         *     verifier.
         *
         *     That cookie is `SameSite=Lax` and must be: the callback is a top-level
         *     navigation *from the identity provider's origin*, and `Strict` would
         *     withhold the cookie there and break every login.
         */
        get: operations["startSSO"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/oidc/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Complete a single sign-on login
         * @description Verifies the returned `state` against the flow cookie, redeems the
         *     authorization code, verifies the ID token, provisions or resolves the
         *     user, and issues a Pivot session — the same session a password login
         *     produces.
         *
         *     The flow cookie is cleared whatever the outcome: a login is single-use,
         *     and leaving it behind invites a replay.
         *
         *     Responds with a redirect for a browser, or the session envelope when
         *     the caller asks for `application/json`.
         */
        get: operations["completeSSO"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/identity-providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The organization's configured identity providers
         * @description Requires `manage_organization`. Pointing an organization at a different
         *     directory is deciding who its users are, which is the same power as
         *     granting roles by another route.
         *
         *     **`clientSecret` is never returned**, to an administrator or anyone
         *     else. `hasClientSecret` says whether one is configured.
         */
        get: operations["listIdentityProviders"];
        put?: never;
        /**
         * Configure an identity provider
         * @description Requires `manage_organization`.
         */
        post: operations["createIdentityProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/identity-providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change an identity provider
         * @description Requires `manage_organization`.
         *
         *     An omitted `clientSecret` keeps the stored one. That is what makes a
         *     write-only field usable: an administration screen reads the provider,
         *     edits the name, and writes it back without ever having seen the secret
         *     and without blanking it.
         */
        put: operations["updateIdentityProvider"];
        post?: never;
        /**
         * Remove an identity provider
         * @description Requires `manage_organization`.
         */
        delete: operations["deleteIdentityProvider"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The built-in roles and what each may do
         * @description Readable by any authenticated caller: which roles exist and what they
         *     mean is documentation, and a role picker needs it. Who *holds* a role
         *     is a different question, answered by the role-assignments endpoint,
         *     which is gated.
         *
         *     `native_query` appears on Analyst and not on Editor deliberately. Raw
         *     SQL bypasses semantic row-level security, so it is a separate grant
         *     rather than something bundled into "can edit".
         */
        get: operations["listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who holds which role
         * @description Requires `manage_roles`.
         */
        get: operations["listRoleAssignments"];
        put?: never;
        /**
         * Give a user or group a role
         * @description Requires `manage_roles` — which is, deliberately, the most dangerous
         *     permission in the API: whoever holds it can grant it to themselves.
         *
         *     Granting the same role twice is a no-op. A subject that does not exist
         *     in the caller's organization is refused as a validation failure rather
         *     than stored as a dangling row.
         */
        post: operations["grantRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organization/role-assignments/{subjectType}/{subjectId}/{role}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Take a role away
         * @description Requires `manage_roles`.
         *
         *     Removing the **last** administrator is refused: an organization with
         *     nobody who can grant roles is recoverable only from the command line,
         *     and the people most likely to reach that state are the least likely to
         *     have shell access. `pivot admin grant-role` is that recovery path.
         */
        delete: operations["revokeRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * End any session in the organization
         * @description Requires `manage_sessions`. This is the administrative counterpart to
         *     `DELETE /api/v1/auth/sessions/{id}`, which only ever ends the caller's
         *     own: scoped to the organization rather than to one user, it is the
         *     right power for responding to a compromise and the wrong one for
         *     managing your own devices, which is why they are separate endpoints
         *     with separate permissions.
         */
        delete: operations["revokeAnySession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/telemetry/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report an error that happened in the browser
         * @description Records a browser error in the server log and returns `204`. There is
         *     no storage, no aggregation and no alerting behind it: a browser error
         *     that lands in the same log as the request that caused it is worth more
         *     than a second system to check.
         *
         *     **Unauthenticated, deliberately.** The errors most worth having are
         *     the ones that happen before login — on the page where logging in was
         *     supposed to work — so requiring a session would collect reports from
         *     exactly the users who are not having the problem. It is defended by
         *     shape instead: a strict rate limit per address, a 16 KiB body cap
         *     rather than the general 1 MiB, and a handler that writes a log line
         *     and nothing else. A report from somebody signed in is attributed to
         *     them.
         *
         *     `traceId` and `requestId` describe the API call that failed, not this
         *     report. The browser reads them from the `traceresponse` and
         *     `X-Request-Id` headers of that failed response rather than inventing
         *     them, which is what makes them findable afterwards. Both are optional
         *     and a trace ID is only available when tracing is enabled.
         *
         *     Unknown fields are ignored here, unlike everywhere else in this API:
         *     the client is a cached bundle in somebody's browser and may be older
         *     than this server, and rejecting its report over a field would lose the
         *     one thing this endpoint exists to collect.
         */
        post: operations["reportBrowserError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whether this Pivot has an administrator yet
         * @description The browser asks this before deciding between the setup page and the
         *     login page. A fresh install would otherwise show a login form that no
         *     password can satisfy.
         *
         *     `initialized` is keyed on organizations rather than users: an
         *     organization with no users is a half-finished setup that nobody can log
         *     into, and calling it initialized would leave the instance permanently
         *     unusable.
         */
        get: operations["getSetupStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first organization and administrator
         * @description Claims an unclaimed Pivot: creates the organization, creates the first
         *     user, grants them the administrator role, and **signs them in** — the
         *     response is the same session envelope `POST /api/v1/auth/login`
         *     returns, and the session cookie is set.
         *
         *     **Unauthenticated, unavoidably**: there is nobody to authenticate as.
         *     That is the security problem of a first run, and it is answered in
         *     three places rather than one — the endpoint refuses once an
         *     organization exists, it requires the setup token the server printed
         *     when it started, and the strict authentication rate limit stands
         *     between an anonymous caller and an unbounded number of Argon2 hashes.
         *
         *     Setup **closes permanently** once it succeeds. There is no path back to
         *     an unclaimed instance short of a new database.
         */
        post: operations["initializeInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Every field is client-supplied and none of it is trusted: strings are
         *     stripped of control characters and truncated before they reach a log,
         *     and the identifiers are checked for shape rather than believed.
         */
        ErrorReport: {
            /**
             * @description The error's message. Truncated rather than rejected if longer.
             * @example Cannot read properties of undefined (reading 'name')
             */
            message: string;
            /**
             * @description How the error surfaced. A render error, a rejected promise and a
             *     plain `window.onerror` fail differently and are usually different
             *     bugs.
             * @example render
             * @example unhandledrejection
             * @example error
             */
            kind?: string;
            /**
             * @description Whatever the browser could produce. Often absent — a cross-origin
             *     script error gives `Script error.` and nothing else.
             */
            stack?: string;
            /**
             * @description The page the error happened on, not the API call that failed.
             * @example https://pivot.example.com/login
             */
            url?: string;
            /**
             * @description The trace of the API call that failed, from its `traceresponse`
             *     header. Present only when the error came from an API call and
             *     tracing is enabled.
             */
            traceId?: string;
            /**
             * @description That same call's `X-Request-Id`. Unlike the trace ID this is always
             *     available, which is why both are here.
             */
            requestId?: string;
        };
        SetupStatus: {
            /** @description True once this Pivot has an organization. */
            initialized: boolean;
            /**
             * @description Whether the setup endpoint demands a token. Safe to publish: an
             *     unclaimed instance says so to whoever asks either way, and a form
             *     that hid the field would produce a rejection nobody could act on.
             */
            tokenRequired: boolean;
        };
        SetupRequest: {
            /** @example Acme Analytics */
            organization: string;
            /** @example Ada Lovelace */
            name?: string;
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /**
             * Format: password
             * @description At least 12 characters. Length is the only rule: composition
             *     requirements push people toward "Password1!" and away from length,
             *     which is what actually matters.
             */
            password: string;
            /**
             * @description The token the server printed when it started. Required unless the
             *     instance was configured with an empty `setup.token`.
             */
            token?: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            currentPassword: string;
            /**
             * Format: password
             * @description At least 12 characters, and different from the current one. Length
             *     is the only composition rule: requiring a digit and a symbol pushes
             *     people toward "Password1!" and away from length, which is what
             *     actually matters.
             */
            newPassword: string;
        };
        LoginRequest: {
            /**
             * Format: email
             * @example ada@example.com
             */
            email: string;
            /** Format: password */
            password: string;
            /**
             * @description The organization slug to authenticate against. May be omitted when
             *     the instance hosts exactly one organization, which is the
             *     self-hosted case. With several it is required — defaulting to one
             *     of them would authenticate people against a tenant they never
             *     named.
             * @example acme
             */
            organization?: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: email */
            email: string;
            name: string;
            avatarUrl?: string;
            /** @example en */
            locale: string;
            /** @example UTC */
            timezone: string;
            isActive: boolean;
        };
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            issuedAt: string;
            /**
             * Format: date-time
             * @description The idle expiry. It moves forward as the session is used.
             */
            expiresAt: string;
            /**
             * Format: date-time
             * @description The hard cap. Never extended, so an actively used session still
             *     ends — without it, a stolen token stays valid indefinitely as long
             *     as the thief keeps using it.
             */
            absoluteExpiresAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            ip?: string;
            userAgent?: string;
            /** @description Whether this is the session making the request. */
            current: boolean;
        };
        SessionEnvelope: {
            user: components["schemas"]["User"];
            session: components["schemas"]["Session"];
            /**
             * @description What the caller may do in their organization.
             *
             *     **Advisory.** It exists so a UI can hide what it cannot do rather
             *     than letting someone discover it by being refused. Every endpoint
             *     enforces independently, so treating this list as the authority
             *     would be a mistake — and an omission from it is never a way in.
             *
             *     Present on `/auth/me`, absent from the login response.
             * @example [
             *       "view_content",
             *       "query"
             *     ]
             */
            permissions?: string[];
        };
        AuthProvider: {
            /** @example okta */
            slug: string;
            /** @example Okta */
            name: string;
        };
        AuthProviderList: {
            providers: components["schemas"]["AuthProvider"][];
        };
        /**
         * @description Which claim means what. Identity providers disagree about names, so
         *     this is configuration rather than a constant. Omitted fields use the
         *     standard OpenID Connect names.
         */
        ClaimMapping: {
            /** @example email */
            email?: string;
            /** @example email_verified */
            emailVerified?: string;
            name?: string;
            /** @example groups */
            groups?: string;
            /**
             * @description Claim name to user-attribute key. Only the claims listed here are
             *     copied: a provider's token routinely carries things Pivot has no
             *     business storing.
             */
            attributes?: {
                [key: string]: string;
            };
        };
        IdentityProvider: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            /** @enum {string} */
            kind: "oidc";
            /** Format: uri */
            issuer: string;
            clientId: string;
            scopes?: string[];
            isEnabled: boolean;
            /** @description Create a Pivot user on first login. */
            autoProvision: boolean;
            /**
             * @description Adopt an existing local account whose **verified** address matches,
             *     on first login. **Off by default, and meant to stay off outside a
             *     migration.** Directories reassign addresses, and with this on the
             *     next holder of an address inherits the previous holder's account.
             */
            linkByEmail: boolean;
            defaultRole: string;
            claimMapping?: components["schemas"]["ClaimMapping"];
            /** Format: int64 */
            version: number;
            /**
             * @description Whether a client secret is configured, without saying what it is.
             *     There is no read path for the secret itself.
             */
            hasClientSecret: boolean;
        };
        IdentityProviderList: {
            providers: components["schemas"]["IdentityProvider"][];
        };
        IdentityProviderRequest: {
            /** @description URL segment; lowercase letters, digits and hyphens. */
            slug: string;
            name: string;
            /**
             * Format: uri
             * @description Must be an `https` URL, or `http` on a loopback host for a local
             *     provider.
             */
            issuer: string;
            clientId: string;
            /**
             * Format: password
             * @description **Write-only.** Omit on update to keep the stored value. May be
             *     empty: PKCE is always used, so a provider configured as a public
             *     client needs no secret.
             */
            clientSecret?: string;
            scopes?: string[];
            isEnabled?: boolean;
            autoProvision?: boolean;
            linkByEmail?: boolean;
            /** @enum {string} */
            defaultRole?: "admin" | "editor" | "analyst" | "viewer";
            claimMapping?: components["schemas"]["ClaimMapping"];
            /**
             * Format: int64
             * @description Required on update, for optimistic concurrency.
             */
            version?: number;
        };
        RoleDescription: {
            /** @example analyst */
            role: string;
            permissions: string[];
        };
        RoleCatalog: {
            roles: components["schemas"]["RoleDescription"][];
        };
        RoleAssignment: {
            /**
             * @description A `group` assignment is a userset: every member of that group holds
             *     the role, including members of groups nested beneath it.
             * @enum {string}
             */
            subjectType: "user" | "group";
            /** Format: uuid */
            subjectId: string;
            /** @example admin */
            role: string;
            /** Format: date-time */
            grantedAt?: string;
        };
        RoleAssignmentList: {
            assignments: components["schemas"]["RoleAssignment"][];
        };
        GrantRoleRequest: {
            /** @enum {string} */
            subjectType: "user" | "group";
            /** Format: uuid */
            subjectId: string;
            /** @enum {string} */
            role: "admin" | "editor" | "analyst" | "viewer";
        };
        SessionList: {
            sessions: components["schemas"]["Session"][];
        };
        HealthResponse: {
            /**
             * @description One of `ok`, `not_ready`, or `shutting_down`.
             * @example ok
             */
            status: string;
            /** @description The running build's version. */
            version: string;
            /** @description Per-dependency results. Present only on the readiness probe. */
            checks?: {
                [key: string]: string;
            };
        };
        ErrorDetail: {
            /**
             * @description The offending field, for validation failures.
             * @example email
             */
            field?: string;
            /** @example is required */
            message: string;
        };
        ErrorBody: {
            /**
             * @description A stable, machine-readable identifier. Independent of the HTTP
             *     status: the status says how the transport should behave, the code
             *     says what went wrong. Branch on this, never on the message.
             * @example PIVOT-REQ-003
             */
            code: string;
            /** @description A human-readable explanation. May change; do not parse it. */
            message: string;
            /** @description Per-field problems, for validation failures. */
            details?: components["schemas"]["ErrorDetail"][];
            /** @description Correlation ID, echoed in the `X-Request-Id` header. */
            requestId?: string;
            /**
             * Format: uri
             * @description Documentation for this error code.
             */
            docs: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
    };
    responses: {
        /** @description The request was malformed */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required, or the tenant could not be resolved */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated, but not permitted */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description No such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description A version conflict or a duplicate */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The body failed validation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The body exceeded the limit for this endpoint */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited. `Retry-After` gives the wait in seconds. */
        TooManyRequests: {
            headers: {
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description A dependency could not be reached. On a gated endpoint this means the
         *     authorization backend was unavailable, so the request was denied
         *     without a decision being made — deliberately distinguishable from 403,
         *     which means a decision was made and it was no.
         */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated; the session cookie is set */
            200: {
                headers: {
                    /** @description The session cookie, `HttpOnly` and `SameSite=Lax`. */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            /**
             * @description Throttled, or the account is locked after repeated failures. The
             *     two are the same status and different codes — `PIVOT-RATE-001`
             *     means "slow down", `PIVOT-AUTH-005` means "this account is locked"
             *     — and they call for different handling, so branch on the code.
             */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out; the session cookie is cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's identity */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description The password was changed and the other sessions ended */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active sessions, most recent activity first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionList"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "ok",
                     *       "version": "1.0.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready for traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Not ready — shutting down, or a dependency is failing */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "not_ready",
                     *       "version": "1.0.0",
                     *       "checks": {
                     *         "database": "error: connection refused"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    listAuthProviders: {
        parameters: {
            query?: {
                /**
                 * @description Organization slug. May be omitted when the instance hosts exactly
                 *     one organization.
                 */
                organization?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The providers to offer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthProviderList"];
                };
            };
        };
    };
    startSSO: {
        parameters: {
            query?: {
                organization?: string;
                /**
                 * @description Where to send the browser after the session exists. **Only a
                 *     same-site absolute path is honored.** An absolute URL, a
                 *     protocol-relative `//host`, or anything a browser might normalize
                 *     into one is dropped — an open redirect on the login path is what
                 *     turns a phishing link into a convincing one.
                 */
                return?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the identity provider */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description No such provider. A disabled provider is deliberately
             *     indistinguishable from one that does not exist.
             */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    completeSSO: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed in; the session cookie is set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            /** @description Signed in; the browser is redirected onward */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /**
             * @description The login could not be verified. Every reason returns this same
             *     answer — which step of a token's validation failed is of interest
             *     to an attacker and to nobody else.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Verified, but not allowed an account here — provisioning is off,
             *     the account is disabled, or the provider sent no verified address.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listIdentityProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The configured providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProviderList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createIdentityProvider: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityProviderRequest"];
            };
        };
        responses: {
            /** @description Configured */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProvider"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    updateIdentityProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityProviderRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentityProvider"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteIdentityProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleCatalog"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listRoleAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every role assignment in the caller's organization */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignmentList"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    grantRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRoleRequest"];
            };
        };
        responses: {
            /** @description The role was granted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subjectType: "user" | "group";
                subjectId: string;
                role: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The role was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /**
             * @description The request was rejected — most usefully, because this is the last
             *     administrator.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    revokeAnySession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session was revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    reportBrowserError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ErrorReport"];
            };
        };
        responses: {
            /** @description The report was recorded */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            413: components["responses"]["PayloadTooLarge"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    getSetupStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The instance status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
    initializeInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description The instance was claimed; the caller is signed in */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            /**
             * @description The setup token is missing or incorrect (`PIVOT-SETUP-002`). One
             *     code for both, because the next step is the same and an
             *     unauthenticated endpoint should not help somebody work out which
             *     half they got right.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description This Pivot already has an administrator (`PIVOT-SETUP-001`), or the
             *     organization or email is taken (`PIVOT-DATA-002`).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
        };
    };
}
