// Code generated by scripts/gen-querier-tracing.py. DO NOT EDIT.

package repo

import (
	"context"

	"github.com/google/uuid"

	"github.com/Mmd4LIFE/pivot/internal/observability"
	"github.com/Mmd4LIFE/pivot/internal/store/model"
)

// tracingQuerier opens a span around every database call.
//
// This is where a trace gets its "what was the database doing" layer. The
// alternative was wrapping the database/sql driver, which reaches deeper --
// it would see the SQL text -- and which means reimplementing Conn, Stmt, Tx
// and every optional interface the two drivers implement. Getting one of those
// wrong silently disables prepared statements or breaks transactions, and the
// span name here already answers the question a trace is opened to ask: which
// operation was slow.
//
// Generated, because sixty-three identical wrappers is precisely the kind of
// thing somebody types wrong once and nobody notices.
type tracingQuerier struct{ next Querier }

// Compile-time assertion. Adding a method to Querier breaks this until the
// decorator is regenerated, which is the point.
var _ Querier = (*tracingQuerier)(nil)

// traced wraps a Querier so that every call opens a span. When tracing is off
// the span is OpenTelemetry's no-op, which costs a couple of pointer
// assignments.
func traced(q Querier) Querier { return &tracingQuerier{next: q} }

func (t *tracingQuerier) CreateOrganization(ctx context.Context, a1 model.CreateOrganizationParams) (model.Organization, error) {
	ctx, span := observability.Start(ctx, "db.CreateOrganization")
	defer span.End()

	return t.next.CreateOrganization(ctx, a1)
}

func (t *tracingQuerier) GetOrganization(ctx context.Context, a1 uuid.UUID) (model.Organization, error) {
	ctx, span := observability.Start(ctx, "db.GetOrganization")
	defer span.End()

	return t.next.GetOrganization(ctx, a1)
}

func (t *tracingQuerier) GetOrganizationBySlug(ctx context.Context, a1 string) (model.Organization, error) {
	ctx, span := observability.Start(ctx, "db.GetOrganizationBySlug")
	defer span.End()

	return t.next.GetOrganizationBySlug(ctx, a1)
}

func (t *tracingQuerier) ListOrganizations(ctx context.Context, a1 model.ListOrganizationsParams) ([]model.Organization, error) {
	ctx, span := observability.Start(ctx, "db.ListOrganizations")
	defer span.End()

	return t.next.ListOrganizations(ctx, a1)
}

func (t *tracingQuerier) UpdateOrganization(ctx context.Context, a1 model.UpdateOrganizationParams) (model.Organization, error) {
	ctx, span := observability.Start(ctx, "db.UpdateOrganization")
	defer span.End()

	return t.next.UpdateOrganization(ctx, a1)
}

func (t *tracingQuerier) SoftDeleteOrganization(ctx context.Context, a1 model.SoftDeleteOrganizationParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SoftDeleteOrganization")
	defer span.End()

	return t.next.SoftDeleteOrganization(ctx, a1)
}

func (t *tracingQuerier) CountOrganizations(ctx context.Context) (int64, error) {
	ctx, span := observability.Start(ctx, "db.CountOrganizations")
	defer span.End()

	return t.next.CountOrganizations(ctx)
}

func (t *tracingQuerier) CreateUser(ctx context.Context, a1 model.CreateUserParams) (model.User, error) {
	ctx, span := observability.Start(ctx, "db.CreateUser")
	defer span.End()

	return t.next.CreateUser(ctx, a1)
}

func (t *tracingQuerier) GetUser(ctx context.Context, a1 model.GetUserParams) (model.User, error) {
	ctx, span := observability.Start(ctx, "db.GetUser")
	defer span.End()

	return t.next.GetUser(ctx, a1)
}

func (t *tracingQuerier) GetUserByEmail(ctx context.Context, a1 model.GetUserByEmailParams) (model.User, error) {
	ctx, span := observability.Start(ctx, "db.GetUserByEmail")
	defer span.End()

	return t.next.GetUserByEmail(ctx, a1)
}

func (t *tracingQuerier) ListUsers(ctx context.Context, a1 model.ListUsersParams) ([]model.User, error) {
	ctx, span := observability.Start(ctx, "db.ListUsers")
	defer span.End()

	return t.next.ListUsers(ctx, a1)
}

func (t *tracingQuerier) UpdateUser(ctx context.Context, a1 model.UpdateUserParams) (model.User, error) {
	ctx, span := observability.Start(ctx, "db.UpdateUser")
	defer span.End()

	return t.next.UpdateUser(ctx, a1)
}

func (t *tracingQuerier) UpdateUserPassword(ctx context.Context, a1 model.UpdateUserPasswordParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.UpdateUserPassword")
	defer span.End()

	return t.next.UpdateUserPassword(ctx, a1)
}

func (t *tracingQuerier) RecordUserLogin(ctx context.Context, a1 model.RecordUserLoginParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RecordUserLogin")
	defer span.End()

	return t.next.RecordUserLogin(ctx, a1)
}

func (t *tracingQuerier) SoftDeleteUser(ctx context.Context, a1 model.SoftDeleteUserParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SoftDeleteUser")
	defer span.End()

	return t.next.SoftDeleteUser(ctx, a1)
}

func (t *tracingQuerier) CountUsers(ctx context.Context, a1 uuid.UUID) (int64, error) {
	ctx, span := observability.Start(ctx, "db.CountUsers")
	defer span.End()

	return t.next.CountUsers(ctx, a1)
}

func (t *tracingQuerier) CreateGroup(ctx context.Context, a1 model.CreateGroupParams) (model.Group, error) {
	ctx, span := observability.Start(ctx, "db.CreateGroup")
	defer span.End()

	return t.next.CreateGroup(ctx, a1)
}

func (t *tracingQuerier) GetGroup(ctx context.Context, a1 model.GetGroupParams) (model.Group, error) {
	ctx, span := observability.Start(ctx, "db.GetGroup")
	defer span.End()

	return t.next.GetGroup(ctx, a1)
}

func (t *tracingQuerier) GetGroupByName(ctx context.Context, a1 model.GetGroupByNameParams) (model.Group, error) {
	ctx, span := observability.Start(ctx, "db.GetGroupByName")
	defer span.End()

	return t.next.GetGroupByName(ctx, a1)
}

func (t *tracingQuerier) ListGroups(ctx context.Context, a1 model.ListGroupsParams) ([]model.Group, error) {
	ctx, span := observability.Start(ctx, "db.ListGroups")
	defer span.End()

	return t.next.ListGroups(ctx, a1)
}

func (t *tracingQuerier) ListChildGroups(ctx context.Context, a1 model.ListChildGroupsParams) ([]model.Group, error) {
	ctx, span := observability.Start(ctx, "db.ListChildGroups")
	defer span.End()

	return t.next.ListChildGroups(ctx, a1)
}

func (t *tracingQuerier) UpdateGroup(ctx context.Context, a1 model.UpdateGroupParams) (model.Group, error) {
	ctx, span := observability.Start(ctx, "db.UpdateGroup")
	defer span.End()

	return t.next.UpdateGroup(ctx, a1)
}

func (t *tracingQuerier) SoftDeleteGroup(ctx context.Context, a1 model.SoftDeleteGroupParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SoftDeleteGroup")
	defer span.End()

	return t.next.SoftDeleteGroup(ctx, a1)
}

func (t *tracingQuerier) AddGroupMember(ctx context.Context, a1 model.AddGroupMemberParams) error {
	ctx, span := observability.Start(ctx, "db.AddGroupMember")
	defer span.End()

	return t.next.AddGroupMember(ctx, a1)
}

func (t *tracingQuerier) RemoveGroupMember(ctx context.Context, a1 model.RemoveGroupMemberParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RemoveGroupMember")
	defer span.End()

	return t.next.RemoveGroupMember(ctx, a1)
}

func (t *tracingQuerier) ListGroupMembers(ctx context.Context, a1 model.ListGroupMembersParams) ([]model.User, error) {
	ctx, span := observability.Start(ctx, "db.ListGroupMembers")
	defer span.End()

	return t.next.ListGroupMembers(ctx, a1)
}

func (t *tracingQuerier) ListUserGroups(ctx context.Context, a1 model.ListUserGroupsParams) ([]model.Group, error) {
	ctx, span := observability.Start(ctx, "db.ListUserGroups")
	defer span.End()

	return t.next.ListUserGroups(ctx, a1)
}

func (t *tracingQuerier) IsGroupMember(ctx context.Context, a1 model.IsGroupMemberParams) (bool, error) {
	ctx, span := observability.Start(ctx, "db.IsGroupMember")
	defer span.End()

	return t.next.IsGroupMember(ctx, a1)
}

func (t *tracingQuerier) UpsertUserAttribute(ctx context.Context, a1 model.UpsertUserAttributeParams) (model.UserAttribute, error) {
	ctx, span := observability.Start(ctx, "db.UpsertUserAttribute")
	defer span.End()

	return t.next.UpsertUserAttribute(ctx, a1)
}

func (t *tracingQuerier) GetUserAttribute(ctx context.Context, a1 model.GetUserAttributeParams) (model.UserAttribute, error) {
	ctx, span := observability.Start(ctx, "db.GetUserAttribute")
	defer span.End()

	return t.next.GetUserAttribute(ctx, a1)
}

func (t *tracingQuerier) ListUserAttributes(ctx context.Context, a1 model.ListUserAttributesParams) ([]model.UserAttribute, error) {
	ctx, span := observability.Start(ctx, "db.ListUserAttributes")
	defer span.End()

	return t.next.ListUserAttributes(ctx, a1)
}

func (t *tracingQuerier) DeleteUserAttribute(ctx context.Context, a1 model.DeleteUserAttributeParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.DeleteUserAttribute")
	defer span.End()

	return t.next.DeleteUserAttribute(ctx, a1)
}

func (t *tracingQuerier) DeleteUserAttributesBySource(ctx context.Context, a1 model.DeleteUserAttributesBySourceParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.DeleteUserAttributesBySource")
	defer span.End()

	return t.next.DeleteUserAttributesBySource(ctx, a1)
}

func (t *tracingQuerier) CreateSession(ctx context.Context, a1 model.CreateSessionParams) (model.Session, error) {
	ctx, span := observability.Start(ctx, "db.CreateSession")
	defer span.End()

	return t.next.CreateSession(ctx, a1)
}

func (t *tracingQuerier) GetSessionByTokenHash(ctx context.Context, a1 string) (model.Session, error) {
	ctx, span := observability.Start(ctx, "db.GetSessionByTokenHash")
	defer span.End()

	return t.next.GetSessionByTokenHash(ctx, a1)
}

func (t *tracingQuerier) TouchSession(ctx context.Context, a1 model.TouchSessionParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.TouchSession")
	defer span.End()

	return t.next.TouchSession(ctx, a1)
}

func (t *tracingQuerier) RevokeSession(ctx context.Context, a1 model.RevokeSessionParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeSession")
	defer span.End()

	return t.next.RevokeSession(ctx, a1)
}

func (t *tracingQuerier) RevokeSessionForUser(ctx context.Context, a1 model.RevokeSessionForUserParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeSessionForUser")
	defer span.End()

	return t.next.RevokeSessionForUser(ctx, a1)
}

func (t *tracingQuerier) RevokeUserSessions(ctx context.Context, a1 model.RevokeUserSessionsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeUserSessions")
	defer span.End()

	return t.next.RevokeUserSessions(ctx, a1)
}

func (t *tracingQuerier) RevokeOtherUserSessions(ctx context.Context, a1 model.RevokeOtherUserSessionsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeOtherUserSessions")
	defer span.End()

	return t.next.RevokeOtherUserSessions(ctx, a1)
}

func (t *tracingQuerier) ListUserSessions(ctx context.Context, a1 model.ListUserSessionsParams) ([]model.Session, error) {
	ctx, span := observability.Start(ctx, "db.ListUserSessions")
	defer span.End()

	return t.next.ListUserSessions(ctx, a1)
}

func (t *tracingQuerier) DeleteExpiredSessions(ctx context.Context, a1 model.DeleteExpiredSessionsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.DeleteExpiredSessions")
	defer span.End()

	return t.next.DeleteExpiredSessions(ctx, a1)
}

func (t *tracingQuerier) ListObjectGrants(ctx context.Context, a1 model.ListObjectGrantsParams) ([]model.RoleAssignment, error) {
	ctx, span := observability.Start(ctx, "db.ListObjectGrants")
	defer span.End()

	return t.next.ListObjectGrants(ctx, a1)
}

func (t *tracingQuerier) ListSubjectGrants(ctx context.Context, a1 model.ListSubjectGrantsParams) ([]model.RoleAssignment, error) {
	ctx, span := observability.Start(ctx, "db.ListSubjectGrants")
	defer span.End()

	return t.next.ListSubjectGrants(ctx, a1)
}

func (t *tracingQuerier) ListGrantsOnObject(ctx context.Context, a1 model.ListGrantsOnObjectParams) ([]model.RoleAssignment, error) {
	ctx, span := observability.Start(ctx, "db.ListGrantsOnObject")
	defer span.End()

	return t.next.ListGrantsOnObject(ctx, a1)
}

func (t *tracingQuerier) GrantRole(ctx context.Context, a1 model.GrantRoleParams) error {
	ctx, span := observability.Start(ctx, "db.GrantRole")
	defer span.End()

	return t.next.GrantRole(ctx, a1)
}

func (t *tracingQuerier) RevokeRole(ctx context.Context, a1 model.RevokeRoleParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeRole")
	defer span.End()

	return t.next.RevokeRole(ctx, a1)
}

func (t *tracingQuerier) RevokeAllForSubject(ctx context.Context, a1 model.RevokeAllForSubjectParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RevokeAllForSubject")
	defer span.End()

	return t.next.RevokeAllForSubject(ctx, a1)
}

func (t *tracingQuerier) CountRoleHolders(ctx context.Context, a1 model.CountRoleHoldersParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.CountRoleHolders")
	defer span.End()

	return t.next.CountRoleHolders(ctx, a1)
}

func (t *tracingQuerier) CreateConnection(ctx context.Context, a1 model.CreateConnectionParams) (model.Connection, error) {
	ctx, span := observability.Start(ctx, "db.CreateConnection")
	defer span.End()

	return t.next.CreateConnection(ctx, a1)
}

func (t *tracingQuerier) GetConnection(ctx context.Context, a1 model.GetConnectionParams) (model.Connection, error) {
	ctx, span := observability.Start(ctx, "db.GetConnection")
	defer span.End()

	return t.next.GetConnection(ctx, a1)
}

func (t *tracingQuerier) GetConnectionBySlug(ctx context.Context, a1 model.GetConnectionBySlugParams) (model.Connection, error) {
	ctx, span := observability.Start(ctx, "db.GetConnectionBySlug")
	defer span.End()

	return t.next.GetConnectionBySlug(ctx, a1)
}

func (t *tracingQuerier) ListConnections(ctx context.Context, a1 uuid.UUID) ([]model.Connection, error) {
	ctx, span := observability.Start(ctx, "db.ListConnections")
	defer span.End()

	return t.next.ListConnections(ctx, a1)
}

func (t *tracingQuerier) UpdateConnection(ctx context.Context, a1 model.UpdateConnectionParams) (model.Connection, error) {
	ctx, span := observability.Start(ctx, "db.UpdateConnection")
	defer span.End()

	return t.next.UpdateConnection(ctx, a1)
}

func (t *tracingQuerier) RecordConnectionTest(ctx context.Context, a1 model.RecordConnectionTestParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RecordConnectionTest")
	defer span.End()

	return t.next.RecordConnectionTest(ctx, a1)
}

func (t *tracingQuerier) SoftDeleteConnection(ctx context.Context, a1 model.SoftDeleteConnectionParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SoftDeleteConnection")
	defer span.End()

	return t.next.SoftDeleteConnection(ctx, a1)
}

func (t *tracingQuerier) CountConnections(ctx context.Context, a1 uuid.UUID) (int64, error) {
	ctx, span := observability.Start(ctx, "db.CountConnections")
	defer span.End()

	return t.next.CountConnections(ctx, a1)
}

func (t *tracingQuerier) CreateIdentityProvider(ctx context.Context, a1 model.CreateIdentityProviderParams) (model.IdentityProvider, error) {
	ctx, span := observability.Start(ctx, "db.CreateIdentityProvider")
	defer span.End()

	return t.next.CreateIdentityProvider(ctx, a1)
}

func (t *tracingQuerier) GetIdentityProvider(ctx context.Context, a1 model.GetIdentityProviderParams) (model.IdentityProvider, error) {
	ctx, span := observability.Start(ctx, "db.GetIdentityProvider")
	defer span.End()

	return t.next.GetIdentityProvider(ctx, a1)
}

func (t *tracingQuerier) GetIdentityProviderBySlug(ctx context.Context, a1 model.GetIdentityProviderBySlugParams) (model.IdentityProvider, error) {
	ctx, span := observability.Start(ctx, "db.GetIdentityProviderBySlug")
	defer span.End()

	return t.next.GetIdentityProviderBySlug(ctx, a1)
}

func (t *tracingQuerier) ListIdentityProviders(ctx context.Context, a1 uuid.UUID) ([]model.IdentityProvider, error) {
	ctx, span := observability.Start(ctx, "db.ListIdentityProviders")
	defer span.End()

	return t.next.ListIdentityProviders(ctx, a1)
}

func (t *tracingQuerier) UpdateIdentityProvider(ctx context.Context, a1 model.UpdateIdentityProviderParams) (model.IdentityProvider, error) {
	ctx, span := observability.Start(ctx, "db.UpdateIdentityProvider")
	defer span.End()

	return t.next.UpdateIdentityProvider(ctx, a1)
}

func (t *tracingQuerier) SoftDeleteIdentityProvider(ctx context.Context, a1 model.SoftDeleteIdentityProviderParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SoftDeleteIdentityProvider")
	defer span.End()

	return t.next.SoftDeleteIdentityProvider(ctx, a1)
}

func (t *tracingQuerier) GetFederatedIdentity(ctx context.Context, a1 model.GetFederatedIdentityParams) (model.FederatedIdentity, error) {
	ctx, span := observability.Start(ctx, "db.GetFederatedIdentity")
	defer span.End()

	return t.next.GetFederatedIdentity(ctx, a1)
}

func (t *tracingQuerier) ListFederatedIdentitiesForUser(ctx context.Context, a1 model.ListFederatedIdentitiesForUserParams) ([]model.FederatedIdentity, error) {
	ctx, span := observability.Start(ctx, "db.ListFederatedIdentitiesForUser")
	defer span.End()

	return t.next.ListFederatedIdentitiesForUser(ctx, a1)
}

func (t *tracingQuerier) LinkFederatedIdentity(ctx context.Context, a1 model.LinkFederatedIdentityParams) (model.FederatedIdentity, error) {
	ctx, span := observability.Start(ctx, "db.LinkFederatedIdentity")
	defer span.End()

	return t.next.LinkFederatedIdentity(ctx, a1)
}

func (t *tracingQuerier) RecordFederatedLogin(ctx context.Context, a1 model.RecordFederatedLoginParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RecordFederatedLogin")
	defer span.End()

	return t.next.RecordFederatedLogin(ctx, a1)
}

func (t *tracingQuerier) GetLoginAttempt(ctx context.Context, a1 model.GetLoginAttemptParams) (model.LoginAttempt, error) {
	ctx, span := observability.Start(ctx, "db.GetLoginAttempt")
	defer span.End()

	return t.next.GetLoginAttempt(ctx, a1)
}

func (t *tracingQuerier) RecordFailedLogin(ctx context.Context, a1 model.RecordFailedLoginParams) (model.LoginAttempt, error) {
	ctx, span := observability.Start(ctx, "db.RecordFailedLogin")
	defer span.End()

	return t.next.RecordFailedLogin(ctx, a1)
}

func (t *tracingQuerier) SetLoginLock(ctx context.Context, a1 model.SetLoginLockParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SetLoginLock")
	defer span.End()

	return t.next.SetLoginLock(ctx, a1)
}

func (t *tracingQuerier) ClearLoginAttempts(ctx context.Context, a1 model.ClearLoginAttemptsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.ClearLoginAttempts")
	defer span.End()

	return t.next.ClearLoginAttempts(ctx, a1)
}

func (t *tracingQuerier) DeleteStaleLoginAttempts(ctx context.Context, a1 model.DeleteStaleLoginAttemptsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.DeleteStaleLoginAttempts")
	defer span.End()

	return t.next.DeleteStaleLoginAttempts(ctx, a1)
}

func (t *tracingQuerier) UpsertCatalogTable(ctx context.Context, a1 model.UpsertCatalogTableParams) (model.CatalogTable, error) {
	ctx, span := observability.Start(ctx, "db.UpsertCatalogTable")
	defer span.End()

	return t.next.UpsertCatalogTable(ctx, a1)
}

func (t *tracingQuerier) UpsertCatalogColumn(ctx context.Context, a1 model.UpsertCatalogColumnParams) (model.CatalogColumn, error) {
	ctx, span := observability.Start(ctx, "db.UpsertCatalogColumn")
	defer span.End()

	return t.next.UpsertCatalogColumn(ctx, a1)
}

func (t *tracingQuerier) SweepCatalogTables(ctx context.Context, a1 model.SweepCatalogTablesParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SweepCatalogTables")
	defer span.End()

	return t.next.SweepCatalogTables(ctx, a1)
}

func (t *tracingQuerier) SweepCatalogColumns(ctx context.Context, a1 model.SweepCatalogColumnsParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SweepCatalogColumns")
	defer span.End()

	return t.next.SweepCatalogColumns(ctx, a1)
}

func (t *tracingQuerier) ListCatalogTables(ctx context.Context, a1 model.ListCatalogTablesParams) ([]model.CatalogTable, error) {
	ctx, span := observability.Start(ctx, "db.ListCatalogTables")
	defer span.End()

	return t.next.ListCatalogTables(ctx, a1)
}

func (t *tracingQuerier) ListCatalogColumns(ctx context.Context, a1 model.ListCatalogColumnsParams) ([]model.CatalogColumn, error) {
	ctx, span := observability.Start(ctx, "db.ListCatalogColumns")
	defer span.End()

	return t.next.ListCatalogColumns(ctx, a1)
}

func (t *tracingQuerier) ListCatalogColumnsForTable(ctx context.Context, a1 model.ListCatalogColumnsForTableParams) ([]model.CatalogColumn, error) {
	ctx, span := observability.Start(ctx, "db.ListCatalogColumnsForTable")
	defer span.End()

	return t.next.ListCatalogColumnsForTable(ctx, a1)
}

func (t *tracingQuerier) GetCatalogTable(ctx context.Context, a1 model.GetCatalogTableParams) (model.CatalogTable, error) {
	ctx, span := observability.Start(ctx, "db.GetCatalogTable")
	defer span.End()

	return t.next.GetCatalogTable(ctx, a1)
}

func (t *tracingQuerier) UpsertCatalogForeignKey(ctx context.Context, a1 model.UpsertCatalogForeignKeyParams) (model.CatalogForeignKey, error) {
	ctx, span := observability.Start(ctx, "db.UpsertCatalogForeignKey")
	defer span.End()

	return t.next.UpsertCatalogForeignKey(ctx, a1)
}

func (t *tracingQuerier) SweepCatalogForeignKeys(ctx context.Context, a1 model.SweepCatalogForeignKeysParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.SweepCatalogForeignKeys")
	defer span.End()

	return t.next.SweepCatalogForeignKeys(ctx, a1)
}

func (t *tracingQuerier) ListCatalogForeignKeys(ctx context.Context, a1 model.ListCatalogForeignKeysParams) ([]model.CatalogForeignKey, error) {
	ctx, span := observability.Start(ctx, "db.ListCatalogForeignKeys")
	defer span.End()

	return t.next.ListCatalogForeignKeys(ctx, a1)
}

func (t *tracingQuerier) StartQueryLog(ctx context.Context, a1 model.StartQueryLogParams) (model.QueryLogEntry, error) {
	ctx, span := observability.Start(ctx, "db.StartQueryLog")
	defer span.End()

	return t.next.StartQueryLog(ctx, a1)
}

func (t *tracingQuerier) FinishQueryLog(ctx context.Context, a1 model.FinishQueryLogParams) (int64, error) {
	ctx, span := observability.Start(ctx, "db.FinishQueryLog")
	defer span.End()

	return t.next.FinishQueryLog(ctx, a1)
}

func (t *tracingQuerier) ListQueryLog(ctx context.Context, a1 model.ListQueryLogParams) ([]model.QueryLogEntry, error) {
	ctx, span := observability.Start(ctx, "db.ListQueryLog")
	defer span.End()

	return t.next.ListQueryLog(ctx, a1)
}

func (t *tracingQuerier) ListRunningQueries(ctx context.Context, a1 uuid.UUID) ([]model.QueryLogEntry, error) {
	ctx, span := observability.Start(ctx, "db.ListRunningQueries")
	defer span.End()

	return t.next.ListRunningQueries(ctx, a1)
}

func (t *tracingQuerier) GetQueryLogEntry(ctx context.Context, a1 model.GetQueryLogEntryParams) (model.QueryLogEntry, error) {
	ctx, span := observability.Start(ctx, "db.GetQueryLogEntry")
	defer span.End()

	return t.next.GetQueryLogEntry(ctx, a1)
}

func (t *tracingQuerier) QueryUsageByUser(
	ctx context.Context, a1 model.QueryUsageByUserParams,
) ([]model.QueryUsage, error) {
	ctx, span := observability.Start(ctx, "db.QueryUsageByUser")
	defer span.End()

	return t.next.QueryUsageByUser(ctx, a1)
}

func (t *tracingQuerier) RequestQueryCancel(
	ctx context.Context, a1 model.RequestQueryCancelParams,
) (int64, error) {
	ctx, span := observability.Start(ctx, "db.RequestQueryCancel")
	defer span.End()

	return t.next.RequestQueryCancel(ctx, a1)
}

func (t *tracingQuerier) ListCancelRequested(ctx context.Context, a1 string) ([]uuid.UUID, error) {
	ctx, span := observability.Start(ctx, "db.ListCancelRequested")
	defer span.End()

	return t.next.ListCancelRequested(ctx, a1)
}

func (t *tracingQuerier) HeartbeatOwnedQueries(ctx context.Context, a1 string) (int64, error) {
	ctx, span := observability.Start(ctx, "db.HeartbeatOwnedQueries")
	defer span.End()

	return t.next.HeartbeatOwnedQueries(ctx, a1)
}
