#!/usr/bin/env python3
"""Generate the tracing decorator for repo.Querier.

The interface has sixty-three methods and every wrapper is identical bar the
name and the signature, which is exactly the kind of thing a person types
wrong once and nobody notices. Generating it means a missing span is
impossible rather than unlikely.

Regenerate with `make gen-tracing` after changing the interface. The compile
will tell you if you forget: the decorator asserts it satisfies Querier.
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "internal/store/repo/querier.go"
TARGET = ROOT / "internal/store/repo/tracing.go"

body = SOURCE.read_text()

start = body.index("type Querier interface {")
depth = 0
for i in range(start, len(body)):
    if body[i] == "{":
        depth += 1
    elif body[i] == "}":
        depth -= 1
        if depth == 0:
            end = i
            break

block = body[start:end]

# Each method is one line: Name(args) (results) -- comments and blanks skipped.
method = re.compile(r"^\t([A-Z]\w*)\((.*?)\)\s*(.*)$")

methods = []
for line in block.splitlines():
    if line.strip().startswith("//") or not line.strip():
        continue
    m = method.match(line)
    if m:
        methods.append((m.group(1), m.group(2).strip(), m.group(3).strip()))

if not methods:
    sys.exit("gen-querier-tracing: parsed no methods; has querier.go changed shape?")

out = ['''// Code generated by scripts/gen-querier-tracing.py. DO NOT EDIT.

package repo

import (
	"context"

	"github.com/google/uuid"

	"github.com/Mmd4LIFE/pivot/internal/observability"
	"github.com/Mmd4LIFE/pivot/internal/store/model"
)

// tracingQuerier opens a span around every database call.
//
// This is where a trace gets its "what was the database doing" layer. The
// alternative was wrapping the database/sql driver, which reaches deeper --
// it would see the SQL text -- and which means reimplementing Conn, Stmt, Tx
// and every optional interface the two drivers implement. Getting one of those
// wrong silently disables prepared statements or breaks transactions, and the
// span name here already answers the question a trace is opened to ask: which
// operation was slow.
//
// Generated, because sixty-three identical wrappers is precisely the kind of
// thing somebody types wrong once and nobody notices.
type tracingQuerier struct{ next Querier }

// Compile-time assertion. Adding a method to Querier breaks this until the
// decorator is regenerated, which is the point.
var _ Querier = (*tracingQuerier)(nil)

// traced wraps a Querier so that every call opens a span. When tracing is off
// the span is OpenTelemetry's no-op, which costs a couple of pointer
// assignments.
func traced(q Querier) Querier { return &tracingQuerier{next: q} }
''']

for name, args, results in methods:
    # Name the parameters so the body can forward them.
    parts = [a.strip() for a in args.split(",")] if args else []
    params = []
    forwarded = []
    for i, typ in enumerate(parts):
        if typ == "context.Context":
            params.append("ctx context.Context")
            forwarded.append("ctx")
        else:
            params.append(f"a{i} {typ}")
            forwarded.append(f"a{i}")

    out.append(f'''
func (t *tracingQuerier) {name}({", ".join(params)}) {results} {{
	ctx, span := observability.Start(ctx, "db.{name}")
	defer span.End()

	return t.next.{name}({", ".join(forwarded)})
}}''')

TARGET.write_text("\n".join(out) + "\n")
print(f"wrote {TARGET.relative_to(ROOT)} with {len(methods)} methods")
